apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/access-log-format: '{"remote_addr": "$remote_addr", "x-forwarded-for": "$http_x_forwarded_for", "request_time": "$request_time", "upstream_response_time": "$upstream_response_time", "request": "$request", "status": "$status"}'
spec:
  ingressClassName: nginx
  rules:
  - host: netflix.bccdevops.site  # Replace with your domain or use a dummy for testing
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netflix-service
            port:
              number: 80