apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netflix-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: netflix.bccdevops.site  # Replace with your domain or use a dummy for testing
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: netflix-service
              port:
                number: 80